### ISSUE TITLE
Intersection of files throws error

### ISSUE THREAD

**Issue by mh11** [1tilly/wgs-exercise#13]
After downloading and creating summery statistics for chromosome 22, I get the following error  during the intersection of the files:
```
Statistic summary for data/1k_chr22_phase3.vcf.gz: 
	Number of records:	1103547
	Number of samples:	2504
	Ts/TV ratio of the 1st ALT:	2.40
	Number of SNPs:	1060388
	Ts/Tv ratio:	2.39
	Number of INDELs:	43230

Statistic summary for data/gnomad_chr22.vcf.gz: 
	Number of records:	3245659
	Number of samples:	0
	Ts/TV ratio of the 1st ALT:	2.13
	Number of SNPs:	2949978
	Ts/Tv ratio:	2.02
	Number of INDELs:	360756

Creating EUR and nonFIN-EUR Subsets...
Subsets created!
Intersecting filtered 1k_EUR with gnomAD...
EUR Intersection created!
Creating EUR stats...
Intersecting filtered 1k_nonFIN with gnomAD...
[E::main_vcfindex] the index file exists. Please use '-f' to overwrite data/gnomad_chr22.vcf.gz.csi

nonFin Intersection created!
Creating nonFin stats...
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    hwe_analysis("data/isec_nonFin/0000.vcf", "nonFin_hwe")
  File "main.py", line 63, in hwe_analysis
    wrapper.get_hwe_count(file_path, 0.05, 0.5, out)
  File "/scratch/mh719/share/1k_project/tmp/wgs-exercise/wrapper.py", line 151, in get_hwe_count
    rc, output = execute_vcftools(file_path, filtering, out_option)
  File "/scratch/mh719/share/1k_project/tmp/wgs-exercise/wrapper.py", line 32, in execute_vcftools
    stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.PIPE)
  File "/usr/local/Cluster-Apps/python/2.7.5/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/Cluster-Apps/python/2.7.5/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

I'm using python 2.7.5 and run the following commands:

```
python main.py --download 22
python main.py --summary data/1k_chr22_phase3.vcf.gz
python main.py --summary data/gnomad_chr22.vcf.gz 
python main.py --files data/1k_chr22_phase3.vcf.gz data/gnomad_chr22.vcf.gz
```
Any ideas what might go wrong?

**Comment by 1tilly** [comment]
Thank you for submitting this issue. It's actually not the creation of the subset rather than the call of the hardy weinberg analysis. While I tested the underlying function, I've missed the quotation marks around the floats for the equilibrium and maf constraints when I added the analysis to the main workflow. 
I fixed it now and will make a test-run over night. 
Sorry for the inconvenience.

**Comment by 1tilly** [comment]
Somehow the vcftools neither output a file, nor an output on stdout. Will hotfix it, so hwe_analysis is not called. I'm working already working on the solution.

**Comment by 1tilly** [comment]
The vcftools do not print the standard information (like the name of the tool and author, the interpreted parameters etc) to stdout but to stderr. Also the creation of an "out.log" file is omitted and the output-option in case of the hwe_analysis via python ignored. 
I now built a workaround, which takes the stderr as output, if the return code is zero and the stdout is empty. 
This should be considered if a further error handling is added.

**Comment by mh11** [comment]
Thanks for the fast respond - I'll give it another go.

**Comment by 1tilly** [comment]
My testrun with smaller files just finished and printed the hwe-analysis correctly. The big run is still ongoing.

**Comment by mh11** [comment]
I only run the last part (which failed) by commenting the intersection stuff out and finished.
